"""Python static-file emitter for compiler_v2."""

from __future__ import annotations

from pathlib import Path
from pprint import pformat
from typing import Any

from roco.compiler_v2.model import StaticBundle
from roco.compiler_v2.sources import file_digest, stable_source_name


HEADER = '''"""Auto-generated by roco.compiler_v2; do not edit by hand."""

from __future__ import annotations

'''


def write_static_files(bundle: StaticBundle, out_dir: Path) -> dict[str, Path]:
    """Write importable Python static modules and return their paths."""
    out_dir.mkdir(parents=True, exist_ok=True)
    init_path = out_dir / "__init__.py"
    lua_enums_path = out_dir / "lua_enums.py"
    pak_axes_path = out_dir / "pak_axes.py"
    manifest_path = out_dir / "manifest.py"

    init_path.write_text(
        HEADER
        + "from .lua_enums import LUA_ENUMS\n"
        + "from .pak_axes import EFFECT_ORDER_NAMES, BUFFBASE_ORDER_NAMES, SKILL_DAM_TYPE_TO_ELEMENT\n"
        + "from .manifest import SOURCE_HASH\n",
        encoding="utf-8",
    )
    lua_enums_path.write_text(_render_lua_enums(bundle), encoding="utf-8")
    pak_axes_path.write_text(_render_pak_axes(bundle), encoding="utf-8")
    manifest_path.write_text(_render_manifest(bundle), encoding="utf-8")

    return {
        "__init__": init_path,
        "lua_enums": lua_enums_path,
        "pak_axes": pak_axes_path,
        "manifest": manifest_path,
    }


def _render_lua_enums(bundle: StaticBundle) -> str:
    parts = [HEADER]
    parts.append(_assign("LUA_ENUMS", bundle.lua_enums))
    for enum_name, values in sorted(bundle.lua_enums.items()):
        parts.append(_assign(_const_name(enum_name), values))
    parts.append(_assign("LUA_ENUM_REFERENCE_COUNTS", bundle.lua_enum_references))
    return "\n".join(parts)


def _render_pak_axes(bundle: StaticBundle) -> str:
    parts = [HEADER]
    parts.append(_assign("BATTLE_GLOBAL_NUMS", bundle.battle_global_nums))
    parts.append(_assign("BATTLE_GLOBAL_LISTS", bundle.battle_global_lists))
    parts.append(_assign("BATTLE_GLOBAL_STRINGS", bundle.battle_global_strings))
    parts.append(_assign("SKILL_DAM_TYPE_NAMES", bundle.skill_dam_type_names))
    parts.append(_assign("SKILL_DAM_TYPE_TO_ELEMENT", bundle.skill_dam_type_to_element))
    parts.append(_assign("SKILL_DAM_TYPE_TO_ELEMENT_NAME", bundle.skill_dam_type_to_element_name))
    parts.append(_assign("SKILL_DAM_TYPE_UNMAPPED", bundle.skill_dam_type_unmapped))
    parts.append(_assign("EFFECT_ORDER_NAMES", bundle.effect_order_names))
    parts.append(_assign("EFFECT_ORDER_COUNTS", bundle.effect_order_counts))
    parts.append(_assign("BUFFBASE_ORDER_NAMES", bundle.buffbase_order_names))
    parts.append(_assign("BUFFBASE_ORDER_COUNTS", bundle.buffbase_order_counts))
    parts.append(_assign("BUFF_BASE_TO_ORDER", bundle.buff_base_to_order))
    parts.append(_assign("BUFF_ID_TO_BASE_IDS", bundle.buff_id_to_base_ids))
    return "\n".join(parts)


def _render_manifest(bundle: StaticBundle) -> str:
    source_files = {
        stable_source_name(path): {
            "name": path.name,
            "sha256": file_digest(path).sha256,
            "size": path.stat().st_size,
        }
        for path in bundle.source_files
    }
    parts = [HEADER]
    parts.append(_assign("SOURCE_HASH", bundle.source_hash))
    parts.append(_assign("SOURCE_FILES", source_files))
    return "\n".join(parts)


def _assign(name: str, value: Any) -> str:
    return f"{name} = {pformat(value, width=100, sort_dicts=True)}\n"


def _const_name(enum_name: str) -> str:
    out: list[str] = []
    prev_lower = False
    for ch in enum_name:
        if ch.isupper() and prev_lower:
            out.append("_")
        out.append(ch.upper())
        prev_lower = ch.islower()
    return "".join(out)
