"""Generate engine runtime handler dispatch artifacts."""

from __future__ import annotations

from pathlib import Path

from roco.engine.kernel.handler_manifest import OP_MODULES, func_to_const, load_handler_order, module_functions


ROOT = Path(__file__).resolve().parents[3]
GEN_DIR = ROOT / "roco" / "generated"
INDICES_PATH = GEN_DIR / "handler_indices.py"
ORDER_PATH = GEN_DIR / "handler_order.py"
TABLE_PATH = GEN_DIR / "handler_table.py"


def write_handler_artifacts() -> dict[str, int]:
    """Write generated handler constants/order/table from engine op modules."""

    handlers = load_handler_order()
    index_map: dict[str, int] = {}

    lines = ["# Auto-generated by roco.engine.kernel.handler_artifacts -- do not edit.", ""]
    for idx, func_name in enumerate(handlers):
        const = func_to_const(func_name)
        index_map[const] = idx
        lines.append(f"{const} = {idx}")
    lines.append("")
    INDICES_PATH.write_text("\n".join(lines), encoding="utf-8")

    order_lines = [
        "# Auto-generated by roco.engine.kernel.handler_artifacts -- do not edit.",
        "",
        "HANDLER_ORDER: tuple[str, ...] = (",
    ]
    for name in handlers:
        order_lines.append(f"    {name!r},")
    order_lines.append(")")
    order_lines.append("")
    ORDER_PATH.write_text("\n".join(order_lines), encoding="utf-8")

    _write_handler_table(handlers)
    return index_map


def _write_handler_table(handlers: tuple[str, ...]) -> None:
    func_to_module: dict[str, str] = {}
    by_module: dict[str, list[str]] = {mod_name: [] for mod_name in OP_MODULES}
    for mod_name, names in module_functions().items():
        for name in names:
            func_to_module[name] = mod_name

    for func_name in handlers:
        if func_name == "_noop":
            continue
        mod_name = func_to_module.get(func_name)
        if mod_name is None:
            raise RuntimeError(f"handler {func_name!r} not found in engine op modules")
        by_module[mod_name].append(func_name)

    lines = [
        "# Auto-generated by roco.engine.kernel.handler_artifacts -- do not edit.",
        "",
        "from roco.engine.kernel.ctx import StageCtx",
        "",
    ]
    for mod_name in OP_MODULES:
        names = by_module[mod_name]
        if not names:
            continue
        lines.append(f"from {mod_name} import (")
        for name in names:
            lines.append(f"    {name},")
        lines.append(")")
    lines.extend([
        "",
        "",
        "def _noop(_ctx: StageCtx, _row: tuple[int, ...]) -> None:",
        "    pass",
        "",
        "",
        "HANDLERS: tuple = (",
    ])
    for idx, name in enumerate(handlers):
        lines.append(f"    {name},  # {idx}")
    lines.extend([")", "", "HANDLER_COUNT = len(HANDLERS)", ""])
    TABLE_PATH.write_text("\n".join(lines), encoding="utf-8")

