"""Marker decorators that declare which pak axis a kernel op covers.

These decorators are **identity functions at runtime** — they do not
register handlers at import time, attach metadata to the wrapped
function, or otherwise touch state.  The compiler reads the decorator
*syntax* via AST (see :mod:`roco.compiler_v2.handler_axes`),
so all arguments must be plain literals (ints, strings, tuples, lists).

Three axes are recognised:

* :func:`handles_buff` — one or more ``Enum.BuffType`` symbols for
  which this op is the primary handler.  The compiler resolves symbols
  through generated Lua enum data before joining ``BUFFBASE_CONF``.
* :func:`handles_prefix` — one or more mixed ``buff_base_id // 1000``
  prefix buckets, expressed as the corresponding ``Enum.BuffType``
  symbol instead of a numeric prefix.
Exact outliers are generated by the compiler from pak structures such as
``BUFF_CONF`` names, types, params, and ``SKILL_CONF.skill_result`` chains.
The engine should not anchor handlers to pak display names.

Each decorator accepts a list of ``(key, alias_or_note)`` tuples so a
single handler can advertise multi-key coverage with one decorator
invocation.  Stacking multiple decorators on the same function is
also fine — the compiler unions them.
"""

from __future__ import annotations

from typing import Callable, Sequence, TypeVar


F = TypeVar("F", bound=Callable[..., None])


def handles_buff(_entries: Sequence[tuple[str, str]]) -> Callable[[F], F]:
    """Declare that the decorated op handles these ``Enum.BuffType`` symbols.

    ``_entries`` is a list of ``("BFT_...", alias)`` tuples.  The
    alias is a short human-readable label (e.g. ``"STAT_MOD"``) used
    by ``PAK_PREFIX_NAMES`` and audit cross-references.  ``alias``
    must be a non-empty string literal so the compiler can pick it up
    via AST.
    """
    def _identity(func: F) -> F:
        return func
    return _identity


def handles_prefix(_entries: Sequence[tuple[str, str]]) -> Callable[[F], F]:
    """Declare that the decorated op covers mixed prefix buckets.

    ``_entries`` is a list of ``("BFT_...", alias)`` tuples.  The
    compiler derives ``prefix = 2000 + Enum.BuffType[symbol]``.  This
    keeps pak numbering in generated data while leaving the engine to
    state only the semantic family it implements.
    """
    def _identity(func: F) -> F:
        return func
    return _identity
