"""Central integer rules consumed by kernel, compiler, and data layers."""

from __future__ import annotations

BPS = 10_000

# Energy and shared battle resources.
STARTING_ENERGY = 10
MAX_ENERGY = 10
FOCUS_ENERGY_GAIN = 5
SIDE_LIVES = 4
WILLPOWER_USES = 2
LEADER_USES = 1
MAGIC_WILLPOWER = 1
MAGIC_LEADER_TRANSFORM = 2
WILLPOWER_POWER = 80
BLOODLINE_LEADER = 18
BLOODLINE_POLLUTANT = 19
HP_FOR_ENERGY_PCT_BPS = 500

# Damage and multiplier rules.
DAMAGE_CONST_BPS = 9_000
STAB_BPS = 15_000
MIN_DAMAGE = 1
RAIN_WATER_BPS = 15_000
TYPE_DOUBLE_WEAK_BPS = 30_000
TYPE_WEAK_BPS = 20_000
TYPE_NEUTRAL_BPS = BPS
TYPE_RESIST_BPS = 5_000
TYPE_DOUBLE_RESIST_BPS = 3_333
WILLPOWER_COUNTER_STATUS_BPS = 15_000

# Residual and mark rules.
BURN_HP_CAP = 1_000
BURN_DAMAGE_BPS = 200
POISON_DAMAGE_BPS = 300
LEECH_DAMAGE_BPS = 800
SANDSTORM_DAMAGE_DENOM = 16
SNOW_FREEZE_STACKS = 2
SLOW_SPEED_REDUCE = 10
MOISTURE_COST_REDUCE = 1
MOMENTUM_COST_UP = 1
METEOR_POWER = 30
THORN_ENTRY_DAMAGE_BPS = 600
SPIRIT_ENTRY_ENERGY_LOSS = 1

MARK_ATTACK_BPS = 1_000
MARK_WIND_BPS = 2_000
MARK_SLUGGISH_BPS = 3_000
MARK_MOMENTUM_BPS = 3_000
MARK_DRAGON_BPS = 4_000
CUTE_DAMAGE_BPS_PER_STACK = 500
CUTE_MAX_STACKS = 15
CUTE_LETHAL_SHIELD_COST = 5
