"""Generate engine runtime handler dispatch artifacts."""

from __future__ import annotations

from pathlib import Path

from roco.engine.kernel.generation.handler_manifest import OP_MODULES, load_handler_order, module_functions


ROOT = Path(__file__).resolve().parents[4]
GEN_DIR = ROOT / "roco" / "generated"
RUNTIME_GEN_DIR = GEN_DIR / "runtime"
ORDER_PATH = RUNTIME_GEN_DIR / "handler_order.py"
TABLE_PATH = RUNTIME_GEN_DIR / "handler_table.py"


def write_handler_artifacts() -> dict[str, int]:
    """Write generated handler constants/order/table from engine op modules."""

    RUNTIME_GEN_DIR.mkdir(parents=True, exist_ok=True)
    (GEN_DIR / "__init__.py").write_text('"""Auto-generated package for compiler_v2 artifacts."""\n', encoding="utf-8")
    (RUNTIME_GEN_DIR / "__init__.py").write_text('"""Engine runtime generated artifacts."""\n', encoding="utf-8")
    handlers = load_handler_order()
    order_lines = [
        "# Auto-generated by roco.engine.kernel.generation.handler_artifacts -- do not edit.",
        "",
        "HANDLER_ORDER: tuple[str, ...] = (",
    ]
    for name in handlers:
        order_lines.append(f"    {name!r},")
    order_lines.append(")")
    order_lines.append("")
    order_lines.append("OP_INDEX: dict[str, int] = {")
    for idx, name in enumerate(handlers):
        order_lines.append(f"    {name!r}: {idx},")
    order_lines.append("}")
    order_lines.extend([
        "",
        "",
        "def op_index(name: str) -> int:",
        "    try:",
        "        return OP_INDEX[name]",
        "    except KeyError as exc:",
        "        raise RuntimeError(f\"unknown engine op {name!r}\") from exc",
    ])
    order_lines.append("")
    ORDER_PATH.write_text("\n".join(order_lines), encoding="utf-8")

    _write_handler_table(handlers)
    return {name: idx for idx, name in enumerate(handlers)}


def _write_handler_table(handlers: tuple[str, ...]) -> None:
    func_to_module: dict[str, str] = {}
    by_module: dict[str, list[str]] = {mod_name: [] for mod_name in OP_MODULES}
    for mod_name, names in module_functions().items():
        for name in names:
            func_to_module[name] = mod_name

    for func_name in handlers:
        if func_name == "_noop":
            continue
        mod_name = func_to_module.get(func_name)
        if mod_name is None:
            raise RuntimeError(f"handler {func_name!r} not found in engine op modules")
        by_module[mod_name].append(func_name)

    lines = [
        "# Auto-generated by roco.engine.kernel.generation.handler_artifacts -- do not edit.",
        "",
        "from roco.engine.kernel.core.ctx import StageCtx",
        "",
    ]
    for mod_name in OP_MODULES:
        names = by_module[mod_name]
        if not names:
            continue
        lines.append(f"from {mod_name} import (")
        for name in names:
            lines.append(f"    {name},")
        lines.append(")")
    lines.extend([
        "",
        "",
        "def _noop(_ctx: StageCtx, _row: tuple[int, ...]) -> None:",
        "    pass",
        "",
        "",
        "HANDLERS: tuple = (",
    ])
    for idx, name in enumerate(handlers):
        lines.append(f"    {name},  # {idx}")
    lines.extend([")", "", "HANDLER_COUNT = len(HANDLERS)", ""])
    TABLE_PATH.write_text("\n".join(lines), encoding="utf-8")
