from __future__ import annotations

from .common import BATTLE_EVENTS_PATH, _assign
from roco.compiler_v2.model import StaticBundle


def write_battle_events(bundle: StaticBundle) -> int:
    events = bundle.lua_enums.get("BattleEvent")
    if events is None:
        raise RuntimeError("static bundle is missing Enum.BattleEvent")

    names_by_value = {int(value): name for name, value in events.items()}
    lines = [
        "# Auto-generated by compiler_v2 from Enum.BattleEvent -- do not edit.",
        "",
        "from __future__ import annotations",
        "",
    ]
    for name, value in sorted(events.items(), key=lambda item: (int(item[1]), item[0])):
        lines.append(f"{name} = {int(value)}")
    lines.append("")
    lines.append(_assign("BATTLE_EVENT_VALUES", dict(sorted(events.items()))).rstrip())
    lines.append(_assign("BATTLE_EVENT_NAMES_BY_VALUE", dict(sorted(names_by_value.items()))).rstrip())
    lines.append("")
    BATTLE_EVENTS_PATH.write_text("\n".join(lines), encoding="utf-8")
    return len(events)
