from __future__ import annotations

from pathlib import Path
from typing import Any

from .common import BUFF_DEFS_PATH, PAK_BIN, _load_json_table


def _as_int_tuple(raw: Any) -> tuple[int, ...]:
    if raw is None:
        return ()
    values = raw if isinstance(raw, (list, tuple)) else (raw,)
    out: list[int] = []
    for value in values:
        try:
            out.append(int(value))
        except (TypeError, ValueError):
            continue
    return tuple(out)


def _reduce_rules(rec: dict) -> tuple[tuple[int, tuple[int, ...]], ...]:
    rules: list[tuple[int, tuple[int, ...]]] = []
    for raw in rec.get("buff_group_reduce") or ():
        if not isinstance(raw, dict):
            continue
        try:
            reduce_type = int(raw.get("reduce_type") or 0)
        except (TypeError, ValueError):
            reduce_type = 0
        rules.append((reduce_type, _as_int_tuple(raw.get("reduce_param"))))
    return tuple(rules)


def build_buff_tables(pak_bin: Path = PAK_BIN) -> dict[str, dict[int, Any]]:
    rows = _load_json_table(pak_bin / "BUFF_CONF.json")
    base_ids: dict[int, tuple[int, ...]] = {}
    buff_type: dict[int, int] = {}
    names: dict[int, str] = {}
    add_des: dict[int, str] = {}
    desc: dict[int, str] = {}
    reduce_rules: dict[int, tuple[tuple[int, tuple[int, ...]], ...]] = {}
    for buff_id, rec in rows.items():
        if not isinstance(buff_id, int):
            continue
        base_ids[buff_id] = _as_int_tuple(rec.get("buff_base_ids"))
        buff_type[buff_id] = int(rec.get("type") or 0)
        names[buff_id] = str(rec.get("name") or "")
        add_des[buff_id] = str(rec.get("add_des") or "")
        desc[buff_id] = str(rec.get("desc") or "")
        reduce_rules[buff_id] = _reduce_rules(rec)
    return {
        "base_ids": base_ids,
        "type": buff_type,
        "names": names,
        "add_des": add_des,
        "desc": desc,
        "reduce_rules": reduce_rules,
    }


def write_buff_defs() -> int:
    tables = build_buff_tables()
    lines = [
        "# Auto-generated by compiler_v2 from BUFF_CONF.json -- do not edit.",
        "",
        "from typing import Any",
        "",
    ]
    for const_name, key in (
        ("BUFF_BASE_IDS", "base_ids"),
        ("BUFF_TYPE", "type"),
        ("BUFF_NAME", "names"),
        ("BUFF_ADD_DES", "add_des"),
        ("BUFF_DESC", "desc"),
        ("BUFF_REDUCE_RULES", "reduce_rules"),
    ):
        lines.append(f"{const_name}: dict[int, Any] = {{")
        for buff_id in sorted(tables[key]):
            lines.append(f"    {buff_id}: {tables[key][buff_id]!r},")
        lines.append("}")
        lines.append("")
    BUFF_DEFS_PATH.write_text("\n".join(lines), encoding="utf-8")
    return len(tables["base_ids"])
