from __future__ import annotations

from pathlib import Path
from typing import Any

from .common import BUFFBASE_PARAMS_PATH, PAK_BIN, _load_json_table


def _normalize_slot(slot: Any) -> tuple[int, ...] | int:
    if isinstance(slot, dict):
        inner = slot.get("params") or []
    elif isinstance(slot, list):
        inner = slot
    else:
        inner = [slot]
    if len(inner) == 1:
        return int(inner[0])
    return tuple(int(v) for v in inner)

def _record_param_tuple(rec: dict) -> tuple:
    raw = rec.get("buffbase_param") or rec.get("params") or []
    return tuple(_normalize_slot(slot) for slot in raw)

def build_buffbase_tables(pak_bin: Path = PAK_BIN) -> dict[str, dict[int, Any]]:
    rows = _load_json_table(pak_bin / "BUFFBASE_CONF.json")
    params: dict[int, tuple] = {}
    order: dict[int, int] = {}
    trigger: dict[int, int] = {}
    for base_id, rec in rows.items():
        if not isinstance(base_id, int):
            continue
        params[base_id] = _record_param_tuple(rec)
        order[base_id] = int(rec.get("buffbase_order") or 0)
        trigger[base_id] = int(rec.get("trigger_type") or 0)
    return {"params": params, "order": order, "trigger": trigger}

def write_buffbase_params() -> int:
    tables = build_buffbase_tables()
    lines = [
        "# Auto-generated by compiler_v2 from BUFFBASE_CONF.json -- do not edit.",
        "",
        "from typing import Any",
        "",
        "BUFFBASE_PARAMS: dict[int, tuple] = {",
    ]
    for base_id in sorted(tables["params"]):
        lines.append(f"    {base_id}: {tables['params'][base_id]!r},")
    lines.append("}")
    lines.append("")
    lines.append("BUFFBASE_ORDER: dict[int, int] = {")
    for base_id in sorted(tables["order"]):
        lines.append(f"    {base_id}: {tables['order'][base_id]},")
    lines.append("}")
    lines.append("")
    lines.append("BUFFBASE_TRIGGER_TYPE: dict[int, int] = {")
    for base_id in sorted(tables["trigger"]):
        lines.append(f"    {base_id}: {tables['trigger'][base_id]},")
    lines.append("}")
    lines.append("")
    BUFFBASE_PARAMS_PATH.write_text("\n".join(lines), encoding="utf-8")
    return len(tables["params"])
