from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from roco.common.packing import MarkIdx

from .common import CANONICAL_ADAPTERS_PATH, PAK_BIN, PAK_DATA, _assign, _load_json_table, _maybe_int
from .marks import mark_note_by_idx


def _canonical_skill_category_from_pak(row: dict[str, Any]) -> str:
    skill_type = _maybe_int(row.get("Skill_Type")) or 0
    damage_type = _maybe_int(row.get("damage_type")) or 0
    if skill_type == 3:
        return "防御"
    if skill_type == 2:
        return "状态"
    if damage_type == 2:
        return "物攻"
    if damage_type in {3, 4}:
        return "魔攻"
    return "状态"

def build_canonical_adapters(pak_data: Path = PAK_DATA, pak_bin: Path = PAK_BIN) -> dict[str, Any]:
    skill_rows = _load_json_table(pak_bin / "SKILL_CONF.json")
    desc_note_rows = _load_json_table(pak_bin / "DESC_NOTE_CONF.json")
    moves = json.loads((pak_data / "moves.json").read_text(encoding="utf-8"))
    category_map: dict[str, str] = {}
    conflicts: dict[str, set[str]] = {}
    for move in moves:
        if not isinstance(move, dict):
            continue
        english = str(move.get("move_category") or "").strip()
        skill_id = _maybe_int(move.get("id"))
        if not english or skill_id is None:
            continue
        row = skill_rows.get(skill_id)
        if row is None:
            continue
        canonical = _canonical_skill_category_from_pak(row)
        existing = category_map.get(english)
        if existing is not None and existing != canonical:
            conflicts.setdefault(english, {existing}).add(canonical)
            continue
        category_map[english] = canonical
    if conflicts:
        details = {key: sorted(values) for key, values in sorted(conflicts.items())}
        raise RuntimeError(f"conflicting move category adapters from moves.json/SKILL_CONF: {details}")

    desc_id_by_note: dict[str, int] = {}
    for desc_id, rec in desc_note_rows.items():
        if not isinstance(desc_id, int):
            continue
        note = str(rec.get("note") or "").strip()
        if note:
            desc_id_by_note[note] = desc_id

    mark_defs: list[tuple[int, str, int, str]] = []
    for idx, note in mark_note_by_idx().items():
        desc_id = desc_id_by_note.get(note)
        if desc_id is None:
            raise RuntimeError(f"DESC_NOTE_CONF missing canonical mark note {note!r}")
        polarity = "positive" if idx.value <= MarkIdx.ATTACK.value or idx == MarkIdx.SLUGGISH else "negative"
        mark_defs.append((desc_id, idx.name.lower(), int(idx.value), polarity))

    return {
        "move_category_to_cn": dict(sorted(category_map.items())),
        "canonical_mark_defs": tuple(mark_defs),
    }

def write_canonical_adapters() -> dict[str, int]:
    tables = build_canonical_adapters()
    lines = [
        "# Auto-generated by compiler_v2 from moves.json + SKILL_CONF.json + DESC_NOTE_CONF.json -- do not edit.",
        "",
        "from __future__ import annotations",
        "",
    ]
    lines.append(_assign("MOVE_CATEGORY_TO_CN", tables["move_category_to_cn"]).rstrip())
    lines.append(_assign("CANONICAL_MARK_DEFS", tables["canonical_mark_defs"]).rstrip())
    lines.append("")
    CANONICAL_ADAPTERS_PATH.write_text("\n".join(lines), encoding="utf-8")
    return {
        "move_category_count": len(tables["move_category_to_cn"]),
        "mark_def_count": len(tables["canonical_mark_defs"]),
    }
