from __future__ import annotations

from roco.common.enums import ELEMENT_NAMES
from roco.compiler_v2.model import StaticBundle

from .common import (
    BATTLE_GLOBALS_PATH,
    PAK_BIN,
    PAK_OPS_PATH,
    SKILL_DAM_TYPES_PATH,
    TYPE_CHART_PATH,
    _assign,
    _load_json_table,
)


def write_battle_globals(bundle: StaticBundle) -> int:
    lines = [
        "# Auto-generated by compiler_v2 from the full BATTLE_GLOBAL_CONFIG.json -- do not edit.",
        "",
        "from __future__ import annotations",
        "",
    ]
    lines.append(_assign("BATTLE_GLOBAL_NUMS", bundle.battle_global_nums).rstrip())
    lines.append(_assign("BATTLE_GLOBAL_LISTS", bundle.battle_global_lists).rstrip())
    lines.append(_assign("BATTLE_GLOBAL_STRINGS", bundle.battle_global_strings).rstrip())
    lines.append("")
    BATTLE_GLOBALS_PATH.write_text("\n".join(lines), encoding="utf-8")
    return len(bundle.battle_global_nums)

def write_skill_dam_types(bundle: StaticBundle) -> int:
    lines = [
        "# Auto-generated by compiler_v2 from Enum.SkillDamType + TYPE_DICTIONARY.json -- do not edit.",
        "",
        "from __future__ import annotations",
        "",
    ]
    lines.append(_assign("SKILL_DAM_TYPE_NAMES", bundle.skill_dam_type_names).rstrip())
    lines.append(_assign("SKILL_DAM_TYPE_TO_ELEMENT", bundle.skill_dam_type_to_element).rstrip())
    lines.append(_assign("SKILL_DAM_TYPE_TO_ELEMENT_NAME", bundle.skill_dam_type_to_element_name).rstrip())
    lines.append(_assign("SKILL_DAM_TYPE_UNMAPPED", bundle.skill_dam_type_unmapped).rstrip())
    lines.append("")
    SKILL_DAM_TYPES_PATH.write_text("\n".join(lines), encoding="utf-8")
    return len(bundle.skill_dam_type_to_element)

def write_pak_ops(bundle: StaticBundle, prefix_aliases: dict[int, str]) -> int:
    buff_rows = _load_json_table(PAK_BIN / "BUFF_CONF.json")
    prefixes: set[int] = set()
    for rec in buff_rows.values():
        for bid in rec.get("buff_base_ids") or []:
            if bid:
                prefixes.add(int(bid) // 1000)
    lines = [
        "# Auto-generated by compiler_v2 from BUFF_CONF + engine handler metadata -- do not edit.",
        "",
        "EFF_BUFF_APPLY = 10001",
        "EFF_DAMAGE = 10002",
        "EFF_STATE_CHANGE = 10003",
        "",
        "PAK_PREFIX_NAMES: dict[int, str] = {",
    ]
    for pfx in sorted(prefixes):
        name = prefix_aliases.get(pfx)
        if name is None:
            order = pfx - 2000
            name = bundle.buffbase_order_names.get(order, f"PREFIX_{pfx}")
        lines.append(f"    {pfx}: {name!r},")
    lines.append("}")
    lines.append("")
    PAK_OPS_PATH.write_text("\n".join(lines), encoding="utf-8")
    return len(prefixes)

def build_type_chart_bps(bundle: StaticBundle) -> tuple[tuple[int, ...], ...]:
    rows = _load_json_table(PAK_BIN / "TYPE_DICTIONARY.json")
    by_short = {rec.get("short_name"): rec for rec in rows.values() if rec.get("short_name")}
    pak_ids: list[int] = []
    for name in ELEMENT_NAMES:
        rec = by_short.get(name)
        if rec is None:
            raise RuntimeError(f"TYPE_DICTIONARY missing short_name={name!r}")
        pak_ids.append(int(rec["id"]))
    neutral = bundle.battle_global_nums["restraint_percent"]
    weak = bundle.battle_global_nums["double_restraint_percent"]
    resist = bundle.battle_global_nums["restrained_percent"]
    n = len(ELEMENT_NAMES)
    chart = [[neutral] * n for _ in range(n)]
    for attacker_idx, attacker_name in enumerate(ELEMENT_NAMES):
        rec = by_short[attacker_name]
        for defender_idx, defender_pak_id in enumerate(pak_ids):
            sign = rec.get(f"type_restraint{defender_pak_id}", 0)
            if sign == 1:
                chart[attacker_idx][defender_idx] = weak
            elif sign == -1:
                chart[attacker_idx][defender_idx] = resist
    return tuple(tuple(row) for row in chart)


def write_type_chart(bundle: StaticBundle) -> int:
    chart = build_type_chart_bps(bundle)
    n = len(ELEMENT_NAMES)
    lines = [
        "# Auto-generated by compiler_v2 from TYPE_DICTIONARY.json -- do not edit.",
        "",
        f"# Element order matches roco.common.enums.ELEMENT_NAMES (length {n}).",
        "TYPE_CHART_BPS: tuple[tuple[int, ...], ...] = (",
    ]
    for idx, name in enumerate(ELEMENT_NAMES):
        lines.append(f"    ({', '.join(str(v) for v in chart[idx])}),  # {idx:2d} {name}")
    lines.append(")")
    lines.append("")
    TYPE_CHART_PATH.write_text("\n".join(lines), encoding="utf-8")
    return n
