from __future__ import annotations

from roco.compiler_v2.model import StaticBundle

from .common import COUNTER_SKILL_TABLE_PATH, PAK_BIN, _load_json_table


def write_counter_skill_table(bundle: StaticBundle) -> int:
    effect_rows = _load_json_table(PAK_BIN / "EFFECT_CONF.json")
    skill_rows = _load_json_table(PAK_BIN / "SKILL_CONF.json")
    counter_skill_ids: set[int] = set()
    for rec in effect_rows.values():
        if int(rec.get("effect_order") or 0) != 31:
            continue
        params = rec.get("effect_param") or []
        if not params or not isinstance(params[0], dict):
            continue
        inner = params[0].get("params") or []
        if not inner:
            continue
        skill_id = int(inner[0])
        if 7000000 <= skill_id < 8000000:
            counter_skill_ids.add(skill_id)
    table: list[tuple[int, int, int, int, int, int, str]] = []
    for skill_id in sorted(counter_skill_ids):
        row = skill_rows.get(skill_id)
        if row is None:
            continue
        dam_para = row.get("dam_para") or [0]
        power = int(dam_para[0] if isinstance(dam_para, list) and dam_para else 0)
        element = bundle.skill_dam_type_to_element.get(int(row.get("skill_dam_type") or 0), 0)
        pak_damage_type = int(row.get("damage_type") or 0)
        pak_skill_type = int(row.get("Skill_Type") or 0)
        if pak_damage_type == 2:
            category = 1
        elif pak_damage_type == 3:
            category = 2
        elif pak_skill_type == 3:
            category = 3
        elif pak_skill_type == 2:
            category = 4
        else:
            category = 0
        table.append((
            skill_id,
            power,
            element,
            category,
            pak_damage_type,
            int(row.get("skill_priority") or 0),
            str(row.get("name") or ""),
        ))
    lines = [
        "# Auto-generated by compiler_v2 from SKILL_CONF + EFFECT_CONF -- do not edit.",
        "",
        "COUNTER_SKILL_TABLE: dict[int, tuple[int, int, int, int, int]] = {",
    ]
    for skill_id, power, element, category, dam_type, priority, name in table:
        lines.append(f"    {skill_id}: ({power}, {element}, {category}, {dam_type}, {priority}),  # {name}")
    lines.append("}")
    lines.append("")
    COUNTER_SKILL_TABLE_PATH.write_text("\n".join(lines), encoding="utf-8")
    return len(table)
