from __future__ import annotations

from pathlib import Path
from typing import Any

from .common import EFFECT_PARAMS_PATH, PAK_BIN, _load_json_table


def _normalize_slot(slot: Any) -> tuple[int, ...] | int:
    if isinstance(slot, dict):
        inner = slot.get("params") or []
    elif isinstance(slot, list):
        inner = slot
    else:
        inner = [slot]
    if len(inner) == 1:
        return int(inner[0])
    return tuple(int(v) for v in inner)


def _record_param_tuple(rec: dict) -> tuple:
    raw = rec.get("effect_param") or rec.get("params") or []
    return tuple(_normalize_slot(slot) for slot in raw)


def build_effect_tables(pak_bin: Path = PAK_BIN) -> dict[str, dict[int, Any]]:
    rows = _load_json_table(pak_bin / "EFFECT_CONF.json")
    params: dict[int, tuple] = {}
    order: dict[int, int] = {}
    effect_type: dict[int, int] = {}
    for effect_id, rec in rows.items():
        if not isinstance(effect_id, int):
            continue
        params[effect_id] = _record_param_tuple(rec)
        order[effect_id] = int(rec.get("effect_order") or 0)
        effect_type[effect_id] = int(rec.get("type") or 0)
    return {"params": params, "order": order, "type": effect_type}


def write_effect_params() -> int:
    tables = build_effect_tables()
    lines = [
        "# Auto-generated by compiler_v2 from EFFECT_CONF.json -- do not edit.",
        "",
        "from typing import Any",
        "",
        "EFFECT_PARAMS: dict[int, tuple] = {",
    ]
    for effect_id in sorted(tables["params"]):
        lines.append(f"    {effect_id}: {tables['params'][effect_id]!r},")
    lines.append("}")
    lines.append("")
    lines.append("EFFECT_ORDER: dict[int, int] = {")
    for effect_id in sorted(tables["order"]):
        lines.append(f"    {effect_id}: {tables['order'][effect_id]},")
    lines.append("}")
    lines.append("")
    lines.append("EFFECT_TYPE: dict[int, int] = {")
    for effect_id in sorted(tables["type"]):
        lines.append(f"    {effect_id}: {tables['type'][effect_id]},")
    lines.append("}")
    lines.append("")
    EFFECT_PARAMS_PATH.write_text("\n".join(lines), encoding="utf-8")
    return len(tables["params"])
