from __future__ import annotations

import ast
import json
import sys

from roco.compiler_v2.handler_registry import func_to_const
from roco.compiler_v2.handler_axes import OP_MODULES

from .common import INDICES_PATH, ORDER_PATH, REGISTRY_PATH, ROOT, TABLE_PATH


def _module_funcs() -> dict[str, list[str]]:
    result: dict[str, list[str]] = {}
    for mod_name in OP_MODULES:
        path = ROOT / (mod_name.replace(".", "/") + ".py")
        tree = ast.parse(path.read_text(encoding="utf-8"))
        result[mod_name] = [
            n.name for n in tree.body
            if isinstance(n, ast.FunctionDef) and n.name.startswith("op_")
        ]
    return result

def _discover_handlers() -> set[str]:
    return {name for names in _module_funcs().values() for name in names}

def _load_registry() -> list[str]:
    if REGISTRY_PATH.exists():
        return json.loads(REGISTRY_PATH.read_text(encoding="utf-8"))["handlers"]
    return ["_noop"]

def _save_registry(handlers: list[str]) -> None:
    payload = {
        "_meta": {
            "version": 2,
            "description": "Append-only handler registry generated by compiler_v2.",
        },
        "handlers": handlers,
    }
    REGISTRY_PATH.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")

def write_handler_artifacts() -> dict[str, int]:
    discovered = _discover_handlers()
    handlers = _load_registry()
    known = set(handlers)
    handlers = handlers + sorted(discovered - known)
    missing = set(handlers[1:]) - discovered
    if missing:
        print(f"WARNING: registry has handlers not in code: {sorted(missing)}", file=sys.stderr)
    _save_registry(handlers)

    index_map: dict[str, int] = {}
    lines = ["# Auto-generated by compiler_v2 from handler_registry.json -- do not edit.", ""]
    for idx, func_name in enumerate(handlers):
        const = func_to_const(func_name)
        index_map[const] = idx
        lines.append(f"{const} = {idx}")
    lines.append("")
    INDICES_PATH.write_text("\n".join(lines), encoding="utf-8")

    order_lines = [
        "# Auto-generated by compiler_v2 from handler_registry.json -- do not edit.",
        "",
        "HANDLER_ORDER: tuple[str, ...] = (",
    ]
    for name in handlers:
        order_lines.append(f"    {name!r},")
    order_lines.append(")")
    order_lines.append("")
    ORDER_PATH.write_text("\n".join(order_lines), encoding="utf-8")
    _write_handler_table(handlers)
    return index_map

def _write_handler_table(handlers: list[str]) -> None:
    func_to_module: dict[str, str] = {}
    by_module: dict[str, list[str]] = {m: [] for m in OP_MODULES}
    for mod_name, names in _module_funcs().items():
        for name in names:
            func_to_module[name] = mod_name
    for func_name in handlers:
        if func_name == "_noop":
            continue
        mod_name = func_to_module.get(func_name)
        if mod_name is None:
            raise RuntimeError(f"handler {func_name!r} not found in op modules")
        by_module[mod_name].append(func_name)

    lines = [
        "# Auto-generated by compiler_v2 -- do not edit.",
        "",
        "from roco.engine.kernel.ctx import StageCtx",
        "",
    ]
    for mod_name in OP_MODULES:
        names = by_module[mod_name]
        if not names:
            continue
        lines.append(f"from {mod_name} import (")
        for name in names:
            lines.append(f"    {name},")
        lines.append(")")
    lines.extend([
        "",
        "",
        "def _noop(_ctx: StageCtx, _row: tuple[int, ...]) -> None:",
        "    pass",
        "",
        "",
        "HANDLERS: tuple = (",
    ])
    for idx, name in enumerate(handlers):
        lines.append(f"    {name},  # {idx}")
    lines.extend([")", "", "HANDLER_COUNT = len(HANDLERS)", ""])
    TABLE_PATH.write_text("\n".join(lines), encoding="utf-8")

def _handler_idx(handler_indices: dict[str, int], handler_name: str) -> int:
    if handler_name == "H_NOOP":
        raise RuntimeError("H_NOOP is not a valid compiler output")
    if handler_name not in handler_indices:
        raise RuntimeError(f"unknown handler {handler_name!r}")
    return handler_indices[handler_name]
