from __future__ import annotations

from roco.common.enums import StatusType
from roco.compiler_v2.buff_immunity_decoders import IMMUNITY_SPECS, load_buff_immunity_table

from .common import BUFF_IMMUNITY_PATH


def write_buff_immunity_table() -> int:
    table = load_buff_immunity_table()
    status_members = {member.name: int(member.value) for member in StatusType}
    status_pairs = []
    for spec in IMMUNITY_SPECS:
        status_name = spec.tag.upper()
        if status_name in status_members:
            status_pairs.append((status_members[status_name], status_name, spec.const_name))
    status_pairs.sort()
    lines = [
        '"""Auto-generated by compiler_v2 from BUFF_CONF.desc immunity phrases -- do not edit."""',
        "",
        "from __future__ import annotations",
        "",
    ]
    max_name_len = max(len(s.const_name) for s in IMMUNITY_SPECS)
    for spec in IMMUNITY_SPECS:
        pad = " " * (max_name_len - len(spec.const_name))
        lines.append(f"{spec.const_name}{pad} = 0x{spec.bit:02X}")
    lines.append("")
    lines.append("BUFF_IMMUNITY_TABLE: dict[int, int] = {")
    for buff_id in sorted(table):
        flags = table[buff_id]
        used = [s for s in IMMUNITY_SPECS if flags & s.bit]
        expr = " | ".join(s.const_name for s in used) if used else "0"
        lines.append(f"    {buff_id}: {expr},")
    lines.append("}")
    lines.append("")
    lines.append("STATUS_IMMUNITY_FLAGS_BY_STATUS_TYPE: dict[int, int] = {")
    for status_value, status_name, const_name in status_pairs:
        lines.append(f"    {status_value}: {const_name},  # StatusType.{status_name}")
    lines.append("}")
    lines.append("")
    BUFF_IMMUNITY_PATH.write_text("\n".join(lines), encoding="utf-8")
    return len(table)
