from __future__ import annotations

from roco.common.mark_indices import MarkIdx

from .common import MARK_GROUPS_PATH, PAK_BIN, _load_json_table


def mark_desc_by_idx() -> dict[MarkIdx, str]:
    out: dict[MarkIdx, str] = {}
    for _buff_id, rec in _mark_buff_rows().items():
        idx = _mark_idx_from_buff(rec)
        if idx is None or idx in out:
            continue
        desc = str(rec.get("name") or rec.get("add_des") or "").strip()
        if desc:
            out[idx] = desc
    return dict(sorted(out.items(), key=lambda item: item[0].value))


def mark_desc_to_idx() -> dict[str, MarkIdx]:
    return {desc: idx for idx, desc in mark_desc_by_idx().items()}


def write_mark_groups(prefix_result: dict) -> tuple[tuple[str, ...], ...]:
    groups: dict[int, set[str]] = {}
    for _buff_id, rec in _mark_buff_rows().items():
        idx = _mark_idx_from_buff(rec)
        if idx is None:
            continue
        for sign in rec.get("buff_groupsigns") or []:
            if sign:
                groups.setdefault(int(sign), set()).add(idx.name)
    cover_groups: list[tuple[str, ...]] = []
    for names_raw in groups.values():
        if len(names_raw) < 2:
            continue
        cover_groups.append(tuple(sorted(names_raw)))
    lines = [
        "# Auto-generated by compiler_v2 from BUFF_CONF.buff_groupsigns -- do not edit.",
        "",
        "from roco.common.mark_indices import MarkIdx",
        "",
        "MARK_COVER_GROUPS: tuple[tuple[MarkIdx, ...], ...] = (",
    ]
    for names in cover_groups:
        lines.append(f"    ({', '.join(f'MarkIdx.{name}' for name in names)}),")
    lines.append(")")
    lines.append("")
    MARK_GROUPS_PATH.write_text("\n".join(lines), encoding="utf-8")
    return tuple(cover_groups)


def _mark_buff_rows() -> dict[int, dict]:
    return {
        buff_id: rec
        for buff_id, rec in _load_json_table(PAK_BIN / "BUFF_CONF.json").items()
        if isinstance(buff_id, int) and int(rec.get("type") or 0) == 4
    }


def _mark_idx_from_buff(rec: dict) -> MarkIdx | None:
    rows = _base_rows(rec)
    if _has_order_params(rows, 7, lambda p: _param_int(p, 4) == 12):
        return MarkIdx.POISON
    if _has_order_params(rows, 32, lambda p: _param_int(p, 3) == -1):
        return MarkIdx.MOISTURE
    if _has_order_params(rows, 94, lambda _p: True):
        return MarkIdx.METEOR
    if _has_order_params(rows, 1, lambda p: _param_int(p, 0) == 6 and _param_int(p, 2) < 0):
        return MarkIdx.SLOW
    if _has_order_params(rows, 17, lambda p: _param_int(p, 0) == 1019001):
        return MarkIdx.SOLAR
    if _has_order_params(rows, 21, lambda p: _param_int(p, 3) > 0):
        return MarkIdx.WIND
    if _has_order_params(rows, 93, lambda p: _param_int(p, 4) == 1 and _param_int(p, 5) == 10):
        return MarkIdx.CHARGE
    if _has_order_params(rows, 49, lambda p: _param_int(p, 0) == 1019011):
        return MarkIdx.SPIRIT
    if _has_order_params(rows, 49, lambda p: _param_int(p, 0) == 1001005):
        return MarkIdx.THORN
    if _has_order_params(rows, 64, lambda p: _param_int(p, 0) == 6):
        return MarkIdx.DRAGON
    has_skill_cost_plus = _has_order_params(rows, 32, lambda p: _param_int(p, 3) > 0)
    has_power_plus = _has_order_params(
        rows,
        23,
        lambda p: _param_int(p, 4) == 1 and _param_int(p, 5) > 0,
    )
    if has_skill_cost_plus and has_power_plus:
        return MarkIdx.MOMENTUM
    if has_power_plus:
        return MarkIdx.ATTACK
    return None


def _base_rows(rec: dict) -> tuple[tuple[int, tuple], ...]:
    buffbase_rows = _load_json_table(PAK_BIN / "BUFFBASE_CONF.json")
    rows: list[tuple[int, tuple]] = []
    for base_id in rec.get("buff_base_ids") or ():
        base = buffbase_rows.get(int(base_id))
        if base is None:
            continue
        rows.append((int(base.get("buffbase_order") or 0), _base_param_slots(base)))
    return tuple(rows)


def _has_order_params(
    rows: tuple[tuple[int, tuple], ...],
    order: int,
    predicate,
) -> bool:
    return any(row_order == order and predicate(params) for row_order, params in rows)


def _base_param_slots(base: dict) -> tuple:
    out: list[object] = []
    for item in base.get("buffbase_param") or []:
        if isinstance(item, dict):
            values = item.get("params") or []
            if len(values) == 1:
                out.append(values[0])
            else:
                out.append(tuple(values))
        else:
            out.append(item)
    return tuple(out)


def _param_int(params_raw: tuple, index: int, default: int = 0) -> int:
    if index >= len(params_raw):
        return default
    value = params_raw[index]
    if isinstance(value, tuple):
        return default
    try:
        return int(value)
    except (TypeError, ValueError):
        return default
