from __future__ import annotations

from pathlib import Path
from typing import Any

from roco.common.enums import Stats

from .common import NATURES_PATH, PAK_BIN, _assign, _load_json_table, _maybe_int


def _runtime_stat_keys() -> tuple[str, ...]:
    return tuple(member.name.lower() for member in sorted(Stats, key=lambda s: s.value))

def build_nature_tables(pak_bin: Path = PAK_BIN) -> dict[str, Any]:
    nature_rows = _load_json_table(pak_bin / "NATURE_CONF.json")
    attribute_rows = _load_json_table(pak_bin / "ATTRIBUTE_CONF.json")

    stat_keys = _runtime_stat_keys()
    nature_attribute_ids = sorted({
        int(rec[field])
        for rec in nature_rows.values()
        for field in ("positive_effect", "negative_effect")
        if _maybe_int(rec.get(field)) is not None
    })
    battle_attrs = sorted(
        (attr_id, rec)
        for attr_id in nature_attribute_ids
        if (rec := attribute_rows.get(attr_id)) is not None
    )
    if len(battle_attrs) != len(stat_keys):
        raise RuntimeError(
            f"NATURE_CONF attribute count {len(battle_attrs)} != Stats count {len(stat_keys)}"
        )
    stat_key_by_attribute_id = {
        attr_id: stat_key
        for (attr_id, _rec), stat_key in zip(battle_attrs, stat_keys, strict=True)
    }
    iv_stat_map = {
        str(rec.get("attribute_name") or rec.get("editor_name")).strip(): stat_key_by_attribute_id[attr_id]
        for attr_id, rec in battle_attrs
        if str(rec.get("attribute_name") or rec.get("editor_name") or "").strip()
    }

    nature_mod_by_id: dict[int, tuple[str, str]] = {}
    nature_effects_by_id: dict[int, tuple[str, int, str, int]] = {}
    player_nature_ids: list[int] = []
    nature_name_to_id: dict[str, int] = {}
    nature_mod: dict[str, tuple[str, str]] = {}
    nature_effects_by_name: dict[str, tuple[str, int, str, int]] = {}

    for nature_id, rec in sorted(nature_rows.items()):
        if not isinstance(nature_id, int):
            continue
        name = str(rec.get("name") or "").strip()
        if not name:
            continue
        positive_attr = int(rec.get("positive_effect") or 0)
        negative_attr = int(rec.get("negative_effect") or 0)
        try:
            positive_key = stat_key_by_attribute_id[positive_attr]
            negative_key = stat_key_by_attribute_id[negative_attr]
        except KeyError as exc:
            raise RuntimeError(f"NATURE_CONF {nature_id} references unknown attribute {exc.args[0]}") from exc
        positive_bps = int(rec.get("positive_effect_proportion") or 0)
        negative_bps = int(rec.get("negative_effect_proportion") or 0)
        pair = (positive_key, negative_key)
        effect = (positive_key, positive_bps, negative_key, negative_bps)
        nature_mod_by_id[nature_id] = pair
        nature_effects_by_id[nature_id] = effect
        if rec.get("is_player_pet_nature") is not True:
            continue
        if name in nature_name_to_id:
            raise RuntimeError(
                f"duplicate player nature name {name!r}: "
                f"{nature_name_to_id[name]} and {nature_id}"
            )
        player_nature_ids.append(nature_id)
        nature_name_to_id[name] = nature_id
        nature_mod[name] = pair
        nature_effects_by_name[name] = effect

    return {
        "attribute_stat_keys": dict(sorted(stat_key_by_attribute_id.items())),
        "iv_stat_map": dict(sorted(iv_stat_map.items())),
        "nature_mod_by_id": dict(sorted(nature_mod_by_id.items())),
        "nature_effects_by_id": dict(sorted(nature_effects_by_id.items())),
        "player_nature_ids": tuple(sorted(player_nature_ids)),
        "nature_name_to_id": dict(sorted(nature_name_to_id.items(), key=lambda item: item[1])),
        "nature_mod": dict(sorted(nature_mod.items(), key=lambda item: nature_name_to_id[item[0]])),
        "nature_effects_by_name": dict(
            sorted(nature_effects_by_name.items(), key=lambda item: nature_name_to_id[item[0]])
        ),
    }

def write_natures() -> int:
    tables = build_nature_tables()
    lines = [
        "# Auto-generated by compiler_v2 from NATURE_CONF.json + ATTRIBUTE_CONF.json -- do not edit.",
        "",
        "from __future__ import annotations",
        "",
    ]
    lines.append(_assign("ATTRIBUTE_STAT_KEYS", tables["attribute_stat_keys"]).rstrip())
    lines.append(_assign("IV_STAT_MAP", tables["iv_stat_map"]).rstrip())
    lines.append(_assign("NATURE_MOD_BY_ID", tables["nature_mod_by_id"]).rstrip())
    lines.append(_assign("NATURE_EFFECTS_BY_ID", tables["nature_effects_by_id"]).rstrip())
    lines.append(_assign("PLAYER_NATURE_IDS", tables["player_nature_ids"]).rstrip())
    lines.append(_assign("NATURE_NAME_TO_ID", tables["nature_name_to_id"]).rstrip())
    lines.append(_assign("NATURE_MOD", tables["nature_mod"]).rstrip())
    lines.append(_assign("NATURE_EFFECTS_BY_NAME", tables["nature_effects_by_name"]).rstrip())
    lines.append("")
    NATURES_PATH.write_text("\n".join(lines), encoding="utf-8")
    return len(tables["nature_mod"])
