from __future__ import annotations

from typing import Any

from roco.common.enums import WeatherType
from roco.compiler_v2.build import build_static_bundle
from roco.compiler_v2.handler_registry import load_handler_indices
from roco.compiler_v2.model import StaticBundle

from .common import WEATHER_DECODERS_PATH, WEATHER_TABLE_PATH, PAK_BIN, _assign, _load_json_table, _maybe_int


def build_weather_tables(bundle: StaticBundle | None = None) -> dict[str, Any]:
    if bundle is None:
        bundle = build_static_bundle()
    rows = _load_json_table(PAK_BIN / "WEATHER_CONF.json")
    weather_symbols_by_value = {
        int(value): str(symbol)
        for symbol, value in bundle.lua_enums["WeatherType"].items()
    }
    weather_rows: dict[int, dict[str, Any]] = {}
    pak_to_kernel: dict[int, int] = {}
    turns_by_pak: dict[int, int] = {}
    for weather_id, rec in sorted(rows.items()):
        if not isinstance(weather_id, int):
            continue
        pak_type = int(rec.get("weather_type") or weather_id)
        pak_symbol = weather_symbols_by_value.get(pak_type, "")
        kernel_name = _kernel_weather_name(pak_symbol)
        kernel_value = -1
        turns = 0
        if kernel_name is not None:
            kernel_value = int(getattr(WeatherType, kernel_name).value)
            turns = _default_weather_turns(kernel_name)
            pak_to_kernel[pak_type] = kernel_value
            turns_by_pak[pak_type] = turns
        weather_rows[pak_type] = {
            "id": weather_id,
            "name": str(rec.get("name") or ""),
            "pak_symbol": pak_symbol,
            "kernel_weather": kernel_value,
            "default_turns": turns,
            "buffs": tuple(
                int(value)
                for value in rec.get("weather_buff") or ()
                if _maybe_int(value) is not None
            ),
            "temperature": _maybe_int(rec.get("temperature")) or 0,
            "weather_params": str(rec.get("weather_params") or ""),
        }
    return {
        "weather_rows": weather_rows,
        "pak_to_kernel": dict(sorted(pak_to_kernel.items())),
        "turns_by_pak": dict(sorted(turns_by_pak.items())),
    }

def write_weather_table(bundle: StaticBundle | None = None) -> int:
    tables = build_weather_tables(bundle)
    rows = tables["weather_rows"]
    lines = [
        "# Auto-generated by compiler_v2 from WEATHER_CONF.json + Enum.WeatherType -- do not edit.",
        "",
        "from __future__ import annotations",
        "",
    ]
    lines.append(_assign("WEATHER_ROWS", rows).rstrip())
    lines.append(_assign("PAK_WEATHER_TYPE_TO_KERNEL", tables["pak_to_kernel"]).rstrip())
    lines.append(_assign("PAK_WEATHER_DEFAULT_TURNS", tables["turns_by_pak"]).rstrip())
    lines.append("")
    WEATHER_TABLE_PATH.write_text("\n".join(lines), encoding="utf-8")
    return len(rows)

def write_weather_decoders(bundle: StaticBundle | None = None) -> int:
    decoded = build_weather_effect_decoders(bundle)
    lines = [
        "# Auto-generated by compiler_v2 from EFFECT_CONF.json -- do not edit.",
        "",
        "from .handler_indices import H_WEATHER",
        "",
        "WEATHER_EFFECT_DECODERS: dict[int, tuple[int, int, int, int, int, int]] = {",
    ]
    for eid, row in sorted(decoded.items()):
        _handler, value, turns, _p2, _p3, _stacks = row
        lines.append(f"    {eid}: (H_WEATHER, {value}, {turns}, 0, 0, 0),  # kernel weather {value}")
    lines.append("}")
    lines.append("")
    WEATHER_DECODERS_PATH.write_text("\n".join(lines), encoding="utf-8")
    return len(decoded)


def build_weather_effect_decoders(
    bundle: StaticBundle | None = None,
    handler_indices: dict[str, int] | None = None,
) -> dict[int, tuple[int, int, int, int, int, int]]:
    if bundle is None:
        bundle = build_static_bundle()
    if handler_indices is None:
        handler_indices = load_handler_indices()
    rows = _load_json_table(PAK_BIN / "EFFECT_CONF.json")
    weather_tables = build_weather_tables(bundle)
    pak_to_kernel = weather_tables["pak_to_kernel"]
    turns_by_pak = weather_tables["turns_by_pak"]
    decoded: dict[int, tuple[int, int, int, int, int, int]] = {}
    h_weather = handler_indices["H_WEATHER"]
    for eid, rec in rows.items():
        if not isinstance(eid, int):
            continue
        if int(rec.get("effect_order") or 0) != 28 or int(rec.get("type") or 0) != 3:
            continue
        params = rec.get("effect_param") or []
        if not params or not isinstance(params[0], dict):
            continue
        inner = params[0].get("params") or []
        if not inner:
            continue
        pak_weather_type = int(inner[0])
        kernel_value = pak_to_kernel.get(pak_weather_type)
        if kernel_value is None:
            continue
        decoded[eid] = (h_weather, kernel_value, turns_by_pak.get(pak_weather_type, 0), 0, 0, 0)
    return dict(sorted(decoded.items()))

def _kernel_weather_name(pak_symbol: str) -> str | None:
    if pak_symbol in ("WT_NONE", "WT_SUNNY"):
        return "NONE"
    if pak_symbol.endswith("RAIN"):
        return "RAIN"
    if pak_symbol in ("WT_SNOW", "WT_SNOWSTORM"):
        return "SNOW"
    if pak_symbol == "WT_SANDSTORM":
        return "SANDSTORM"
    return None

def _default_weather_turns(kernel_name: str) -> int:
    return 0 if kernel_name == "NONE" else 8
