"""Effect primitive registry shared by import-time validation and runtime."""

from __future__ import annotations

from roco.compiler.effect_model import EffectTag


IMPLEMENTED_EFFECT_TAGS = frozenset({
    EffectTag.DAMAGE,
    EffectTag.DAMAGE_REDUCTION,
    EffectTag.ENERGY_ALL_IN,
    EffectTag.HEAL_HP,
    EffectTag.HEAL_ENERGY,
    EffectTag.STEAL_ENERGY,
    EffectTag.ENEMY_LOSE_ENERGY,
    EffectTag.LIFE_DRAIN,
    EffectTag.SELF_BUFF,
    EffectTag.SELF_DEBUFF,
    EffectTag.ENEMY_DEBUFF,
    EffectTag.DISPEL_BUFFS,
    EffectTag.BURN,
    EffectTag.POISON,
    EffectTag.FREEZE,
    EffectTag.LEECH,
    EffectTag.METEOR,
    EffectTag.POISON_MARK,
    EffectTag.MOISTURE_MARK,
    EffectTag.DRAGON_MARK,
    EffectTag.WIND_MARK,
    EffectTag.CHARGE_MARK,
    EffectTag.SOLAR_MARK,
    EffectTag.ATTACK_MARK,
    EffectTag.SLOW_MARK,
    EffectTag.SLUGGISH_MARK,
    EffectTag.SPIRIT_MARK,
    EffectTag.METEOR_MARK,
    EffectTag.THORN_MARK,
    EffectTag.MOMENTUM_MARK,
    EffectTag.DISPEL_ENEMY_MARKS,
    EffectTag.CONVERT_MARKS_TO_BURN,
    EffectTag.DISPEL_MARKS_TO_BURN,
    EffectTag.CONSUME_MARKS_HEAL,
    EffectTag.MARKS_TO_METEOR,
    EffectTag.STEAL_MARKS,
    EffectTag.ENERGY_COST_PER_ENEMY_MARK,
    EffectTag.DISPEL_MARKS,
    EffectTag.STAT_SCALE_METEOR_MARKS_PER_TURN,
    EffectTag.MARK_POWER_PER_METEOR,
    EffectTag.MARK_FREEZE_TO_METEOR,
    EffectTag.MARK_STACK_NO_REPLACE,
    EffectTag.MARK_STACK_DEBUFFS,
    EffectTag.FORCE_SWITCH,
    EffectTag.WEATHER,
    EffectTag.ENEMY_ENERGY_COST_UP,
    EffectTag.HP_FOR_ENERGY,
    EffectTag.PERMANENT_MOD,
    EffectTag.SKILL_MOD,
    EffectTag.NEXT_ATTACK_MOD,
    EffectTag.POWER_DYNAMIC,
    EffectTag.AGILITY,
    EffectTag.FAINT_NO_MP_LOSS,
    EffectTag.ENERGY_REGEN_PER_TURN,
    EffectTag.POWER_MULTIPLIER_BUFF,
    EffectTag.FIRST_STRIKE_POWER_BONUS,
    EffectTag.AUTO_SWITCH_ON_ZERO_ENERGY,
    EffectTag.AUTO_SWITCH_AFTER_ACTION,
    EffectTag.LEAVE_ENERGY_REFILL,
    EffectTag.BARREL_STATE,
    EffectTag.ENERGY_NO_CAP,
    EffectTag.BURN_NO_DECAY,
    EffectTag.EXTRA_POISON_TICK,
    EffectTag.EXTRA_FREEZE_ON_FREEZE,
    EffectTag.BURST_POWER_BONUS,
    EffectTag.BURST_ENEMY_COST_UP,
    EffectTag.BURST_ELEMENT_COST_REDUCE,
    EffectTag.BURST_EXTEND,
    EffectTag.CUTE_GAIN,
    EffectTag.CUTE_BOTH,
    EffectTag.CUTE_ENEMY_GAIN,
})
