"""JSONL + markdown rendering and the on-disk drift check.

Output is deliberately deterministic: :func:`render_jsonl` sorts keys per
record, :func:`render_markdown` walks families in catalog order, and
:func:`check_outputs` does a literal text compare against the on-disk
artifacts.

Public surface used by the CLI entry point:

* :func:`render_jsonl`
* :func:`render_markdown`
* :func:`check_outputs`
"""

from __future__ import annotations

import sys
from collections import defaultdict
import json

from .paths import CATALOG_JSONL, CATALOG_MD


def render_jsonl(families: list[dict]) -> str:
    return "\n".join(json.dumps(f, ensure_ascii=False, sort_keys=True) for f in families) + "\n"


def render_markdown(families: list[dict]) -> str:
    lines: list[str] = []
    lines.append("# Effect Family Audit\n")
    lines.append(
        "_Auto-generated by `roco/compiler_v2/build_effect_families.py`. "
        "Do not edit by hand. Re-run with `uv run python -m roco.compiler_v2.build_effect_families`._\n"
    )
    lines.append(f"Total families: **{len(families)}**\n")
    by_status: dict[str, int] = defaultdict(int)
    for f in families:
        by_status[f["coverage_status"]] += 1
    lines.append("## Coverage status\n")
    for status in sorted(by_status):
        lines.append(f"- `{status}`: {by_status[status]}")
    lines.append("")

    for f in families:
        lines.append(f"## `{f['family_key']}` — {f['source_table']}")
        lines.append("")
        lines.append(f"- count: **{f['count']}** | coverage: `{f['coverage_status']}` "
                     f"| used_consumer_count: {f['used_consumer_count']}")
        if f["editor_names"]:
            lines.append(f"- editor_names: {', '.join(f['editor_names'][:10])}")
        if f.get("source_descriptions"):
            lines.append(f"- source_descriptions: {', '.join(f['source_descriptions'][:5])}")
        lines.append(f"- example_source_ids: {f['example_source_ids']}")
        lines.append(f"- coverage_breakdown: {f['coverage_breakdown']}")
        if f["sample_skill_consumers"]:
            lines.append("- sample_skill_consumers:")
            for c in f["sample_skill_consumers"]:
                desc = c.get("source_desc") or c.get("desc", "")
                lines.append(f"    - `{c['source_id']}` {c['name']} — {desc[:80]}")
        if f["sample_ability_consumers"]:
            lines.append("- sample_ability_consumers:")
            for c in f["sample_ability_consumers"]:
                desc = c.get("source_desc") or c.get("desc", "")
                lines.append(f"    - `{c['source_id']}` {c['name']} — {desc[:80]}")
        if f["desc_note_refs"]:
            lines.append("- desc_note_refs:")
            for d in f["desc_note_refs"]:
                lines.append(f"    - `desc_{d['desc_id']}` {d['note']}")
        if f["pak_evidence"]:
            lines.append("- pak_evidence:")
            for e in f["pak_evidence"]:
                lines.append(f"    - {e}")
        lines.append("")
    return "\n".join(lines)


def check_outputs(new_jsonl: str, new_md: str) -> int:
    """Compare freshly-rendered output strings against the on-disk artifacts.

    Returns 0 if both files exist and match byte-for-byte, 1 otherwise
    (after writing a per-file drift report to stderr).  Used by the
    ``--check`` mode of the CLI entry point.
    """
    drift: list[str] = []
    for path, fresh in ((CATALOG_JSONL, new_jsonl), (CATALOG_MD, new_md)):
        if not path.exists():
            drift.append(f"missing: {path}")
            continue
        on_disk = path.read_text(encoding="utf-8")
        if on_disk != fresh:
            drift.append(f"stale: {path}")
    if drift:
        sys.stderr.write(
            "effect family catalog is out of date; re-run "
            "`uv run python -m roco.compiler_v2.build_effect_families`:\n"
        )
        for d in drift:
            sys.stderr.write(f"  - {d}\n")
        return 1
    return 0
